### ISSUE TITLE
USB host not working

### ISSUE THREAD

**Issue by irpaej** [MrBlueXav/Dekrispator_v2#5]
Hi MrBlueXav,

First, thanks a lot for sharing your code, this synth seems very fun!

I'm a bit experienced with STM32F4 :) I wanted to use your code and modify some parameters of the synth to experiment with sounds. I also use a nanoKnontrol 2 (and some other USB controllers).

I work on STM32F4_DISCOVERY and I use the Coocox IDE. First, I managed to compile and make the code working with my IDE and hardware, this is a great step :)

The function USBH_UserProcess_callback works pefeclty, I can see on the 4 leds if my USB device is ready or disconnected or start mode.

But now I realize that there is a problem with the called function **USBH_MIDI_Process**:

`static USBH_StatusTypeDef USBH_MIDI_Process (USBH_HandleTypeDef *phost)
{
    USBH_StatusTypeDef status = USBH_BUSY;
    USBH_StatusTypeDef req_status = USBH_OK;
    MIDI_HandleTypeDef *MIDI_Handle =  phost->pActiveClass->pData;

```
HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_14);

switch(MIDI_Handle->state)
{

case MIDI_IDLE_STATE:
    status = USBH_OK;
    break;

case MIDI_TRANSFER_DATA:

    MIDI_ProcessTransmission(phost);
    MIDI_ProcessReception(phost);
    break;

case MIDI_ERROR_STATE:
    req_status = USBH_ClrFeature(phost, 0x00);

    if(req_status == USBH_OK )
    {
        /*Change the state to waiting*/
        MIDI_Handle->state = MIDI_IDLE_STATE ;
    }
    break;

default:
    break;

}

return status;
```

}`

_phost->pActiveClass->pData_ is always equal to '0' so I guess it doesn't even exist :)

_MIDI_Handle->state_ is always unknown, so the switch always case to default, even when I use the USB controller.

Do you have an idea of what happen?

Thanks a lot for your help, have a great day!

Jean

**Comment by JSB2500** [comment]
Dear Xavier

Firstly, many thanks for creating midi_USBH.h/midi_USBH.c!

I found a problem with MIDI_Handle->data_tx_state being essentially a random value, causing my code to try sending MIDI data prematurely. The problem happened with some builds but not others.

The problem is around line 96 of midi_USBH.c. It allocates a MIDI_HandleTypeDef struct but does not zero it. As a result it is full of rubbish that can cause the program to fail.

To solve it, I inserted this line after the memory allocation: 
`USBH_memset(phost->pActiveClass->pData, 0, sizeof(MIDI_HandleTypeDef));`

I hope this is useful.

John.
